# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QSpacerItem,
    QStackedWidget, QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1016, 808)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_5 = QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.daohang = QFrame(self.centralwidget)
        self.daohang.setObjectName(u"daohang")
        self.daohang.setStyleSheet(u"background-color: rgb(94, 92, 100);")
        self.daohang.setFrameShape(QFrame.StyledPanel)
        self.daohang.setFrameShadow(QFrame.Plain)
        self.gridLayout = QGridLayout(self.daohang)
        self.gridLayout.setObjectName(u"gridLayout")
        self.pushButton_5 = QPushButton(self.daohang)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)

        self.line = QFrame(self.daohang)
        self.line.setObjectName(u"line")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(29)
        sizePolicy1.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy1)
        self.line.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.temperature_btn = QPushButton(self.daohang)
        self.temperature_btn.setObjectName(u"temperature_btn")
        self.temperature_btn.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout.addWidget(self.temperature_btn)

        self.history_btn = QPushButton(self.daohang)
        self.history_btn.setObjectName(u"history_btn")
        self.history_btn.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout.addWidget(self.history_btn)

        self.client_setup_btn = QPushButton(self.daohang)
        self.client_setup_btn.setObjectName(u"client_setup_btn")
        self.client_setup_btn.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout.addWidget(self.client_setup_btn)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.exit_btn = QPushButton(self.daohang)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout.addWidget(self.exit_btn)


        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)


        self.gridLayout_5.addWidget(self.daohang, 0, 0, 1, 1)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_4 = QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.stackedWidget = QStackedWidget(self.frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.page1_main = QWidget()
        self.page1_main.setObjectName(u"page1_main")
        self.gridLayout_2 = QGridLayout(self.page1_main)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.fdn1in_btn = QPushButton(self.page1_main)
        self.fdn1in_btn.setObjectName(u"fdn1in_btn")
        self.fdn1in_btn.setMinimumSize(QSize(0, 30))
        font = QFont()
        font.setFamilies([u"Suruma"])
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.fdn1in_btn.setFont(font)
        self.fdn1in_btn.setMouseTracking(True)
        self.fdn1in_btn.setTabletTracking(False)
        self.fdn1in_btn.setContextMenuPolicy(Qt.DefaultContextMenu)
#if QT_CONFIG(statustip)
        self.fdn1in_btn.setStatusTip(u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528")
#endif // QT_CONFIG(statustip)
        self.fdn1in_btn.setCheckable(True)
        self.fdn1in_btn.setAutoRepeatDelay(301)
        self.fdn1in_btn.setAutoDefault(False)
        self.fdn1in_btn.setFlat(False)

        self.gridLayout_2.addWidget(self.fdn1in_btn, 0, 0, 1, 1)

        self.fdn1intm = QLabel(self.page1_main)
        self.fdn1intm.setObjectName(u"fdn1intm")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.fdn1intm.sizePolicy().hasHeightForWidth())
        self.fdn1intm.setSizePolicy(sizePolicy2)
        self.fdn1intm.setMinimumSize(QSize(100, 30))
        self.fdn1intm.setFont(font)
        self.fdn1intm.setAutoFillBackground(False)
        self.fdn1intm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn1intm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn1intm.setFrameShape(QFrame.Panel)
        self.fdn1intm.setFrameShadow(QFrame.Sunken)
        self.fdn1intm.setTextFormat(Qt.AutoText)
        self.fdn1intm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn1intm, 0, 1, 1, 1)

        self.fdn1in_btn_2 = QPushButton(self.page1_main)
        self.fdn1in_btn_2.setObjectName(u"fdn1in_btn_2")
        self.fdn1in_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn1in_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn1in_btn_2, 0, 2, 1, 1)

        self.fdn1intm_2 = QLabel(self.page1_main)
        self.fdn1intm_2.setObjectName(u"fdn1intm_2")
        sizePolicy2.setHeightForWidth(self.fdn1intm_2.sizePolicy().hasHeightForWidth())
        self.fdn1intm_2.setSizePolicy(sizePolicy2)
        self.fdn1intm_2.setMinimumSize(QSize(100, 30))
        self.fdn1intm_2.setFont(font)
        self.fdn1intm_2.setAutoFillBackground(False)
        self.fdn1intm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn1intm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn1intm_2.setFrameShape(QFrame.Panel)
        self.fdn1intm_2.setFrameShadow(QFrame.Sunken)
        self.fdn1intm_2.setTextFormat(Qt.AutoText)
        self.fdn1intm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn1intm_2, 0, 3, 1, 1)

        self.fdn1in_btn_3 = QPushButton(self.page1_main)
        self.fdn1in_btn_3.setObjectName(u"fdn1in_btn_3")
        self.fdn1in_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn1in_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn1in_btn_3, 0, 4, 1, 1)

        self.fdn1intm_3 = QLabel(self.page1_main)
        self.fdn1intm_3.setObjectName(u"fdn1intm_3")
        sizePolicy2.setHeightForWidth(self.fdn1intm_3.sizePolicy().hasHeightForWidth())
        self.fdn1intm_3.setSizePolicy(sizePolicy2)
        self.fdn1intm_3.setMinimumSize(QSize(100, 30))
        self.fdn1intm_3.setFont(font)
        self.fdn1intm_3.setAutoFillBackground(False)
        self.fdn1intm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn1intm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn1intm_3.setFrameShape(QFrame.Panel)
        self.fdn1intm_3.setFrameShadow(QFrame.Sunken)
        self.fdn1intm_3.setTextFormat(Qt.AutoText)
        self.fdn1intm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn1intm_3, 0, 5, 1, 1)

        self.fdn1out_brn = QPushButton(self.page1_main)
        self.fdn1out_brn.setObjectName(u"fdn1out_brn")
        self.fdn1out_brn.setMinimumSize(QSize(0, 30))
        self.fdn1out_brn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn1out_brn, 1, 0, 1, 1)

        self.fdn1outtm = QLabel(self.page1_main)
        self.fdn1outtm.setObjectName(u"fdn1outtm")
        sizePolicy2.setHeightForWidth(self.fdn1outtm.sizePolicy().hasHeightForWidth())
        self.fdn1outtm.setSizePolicy(sizePolicy2)
        self.fdn1outtm.setMinimumSize(QSize(100, 30))
        self.fdn1outtm.setFont(font)
        self.fdn1outtm.setAutoFillBackground(False)
        self.fdn1outtm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn1outtm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn1outtm.setFrameShape(QFrame.Panel)
        self.fdn1outtm.setFrameShadow(QFrame.Sunken)
        self.fdn1outtm.setTextFormat(Qt.AutoText)
        self.fdn1outtm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn1outtm, 1, 1, 1, 1)

        self.fdn1out_brn_2 = QPushButton(self.page1_main)
        self.fdn1out_brn_2.setObjectName(u"fdn1out_brn_2")
        self.fdn1out_brn_2.setMinimumSize(QSize(0, 30))
        self.fdn1out_brn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn1out_brn_2, 1, 2, 1, 1)

        self.fdn1outtm_2 = QLabel(self.page1_main)
        self.fdn1outtm_2.setObjectName(u"fdn1outtm_2")
        sizePolicy2.setHeightForWidth(self.fdn1outtm_2.sizePolicy().hasHeightForWidth())
        self.fdn1outtm_2.setSizePolicy(sizePolicy2)
        self.fdn1outtm_2.setMinimumSize(QSize(100, 30))
        self.fdn1outtm_2.setFont(font)
        self.fdn1outtm_2.setAutoFillBackground(False)
        self.fdn1outtm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn1outtm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn1outtm_2.setFrameShape(QFrame.Panel)
        self.fdn1outtm_2.setFrameShadow(QFrame.Sunken)
        self.fdn1outtm_2.setTextFormat(Qt.AutoText)
        self.fdn1outtm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn1outtm_2, 1, 3, 1, 1)

        self.fdn1out_brn_3 = QPushButton(self.page1_main)
        self.fdn1out_brn_3.setObjectName(u"fdn1out_brn_3")
        self.fdn1out_brn_3.setMinimumSize(QSize(0, 30))
        self.fdn1out_brn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn1out_brn_3, 1, 4, 1, 1)

        self.fdn1outtm_3 = QLabel(self.page1_main)
        self.fdn1outtm_3.setObjectName(u"fdn1outtm_3")
        sizePolicy2.setHeightForWidth(self.fdn1outtm_3.sizePolicy().hasHeightForWidth())
        self.fdn1outtm_3.setSizePolicy(sizePolicy2)
        self.fdn1outtm_3.setMinimumSize(QSize(100, 30))
        self.fdn1outtm_3.setFont(font)
        self.fdn1outtm_3.setAutoFillBackground(False)
        self.fdn1outtm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn1outtm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn1outtm_3.setFrameShape(QFrame.Panel)
        self.fdn1outtm_3.setFrameShadow(QFrame.Sunken)
        self.fdn1outtm_3.setTextFormat(Qt.AutoText)
        self.fdn1outtm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn1outtm_3, 1, 5, 1, 1)

        self.fdn2in_btn = QPushButton(self.page1_main)
        self.fdn2in_btn.setObjectName(u"fdn2in_btn")
        self.fdn2in_btn.setMinimumSize(QSize(0, 30))
        self.fdn2in_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn2in_btn, 2, 0, 1, 1)

        self.fdn2intm = QLabel(self.page1_main)
        self.fdn2intm.setObjectName(u"fdn2intm")
        sizePolicy2.setHeightForWidth(self.fdn2intm.sizePolicy().hasHeightForWidth())
        self.fdn2intm.setSizePolicy(sizePolicy2)
        self.fdn2intm.setMinimumSize(QSize(100, 30))
        self.fdn2intm.setFont(font)
        self.fdn2intm.setAutoFillBackground(False)
        self.fdn2intm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn2intm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn2intm.setFrameShape(QFrame.Panel)
        self.fdn2intm.setFrameShadow(QFrame.Sunken)
        self.fdn2intm.setTextFormat(Qt.AutoText)
        self.fdn2intm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn2intm, 2, 1, 1, 1)

        self.fdn2in_btn_2 = QPushButton(self.page1_main)
        self.fdn2in_btn_2.setObjectName(u"fdn2in_btn_2")
        self.fdn2in_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn2in_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn2in_btn_2, 2, 2, 1, 1)

        self.fdn2intm_2 = QLabel(self.page1_main)
        self.fdn2intm_2.setObjectName(u"fdn2intm_2")
        sizePolicy2.setHeightForWidth(self.fdn2intm_2.sizePolicy().hasHeightForWidth())
        self.fdn2intm_2.setSizePolicy(sizePolicy2)
        self.fdn2intm_2.setMinimumSize(QSize(100, 30))
        self.fdn2intm_2.setFont(font)
        self.fdn2intm_2.setAutoFillBackground(False)
        self.fdn2intm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn2intm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn2intm_2.setFrameShape(QFrame.Panel)
        self.fdn2intm_2.setFrameShadow(QFrame.Sunken)
        self.fdn2intm_2.setTextFormat(Qt.AutoText)
        self.fdn2intm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn2intm_2, 2, 3, 1, 1)

        self.fdn2in_btn_3 = QPushButton(self.page1_main)
        self.fdn2in_btn_3.setObjectName(u"fdn2in_btn_3")
        self.fdn2in_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn2in_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn2in_btn_3, 2, 4, 1, 1)

        self.fdn2intm_3 = QLabel(self.page1_main)
        self.fdn2intm_3.setObjectName(u"fdn2intm_3")
        sizePolicy2.setHeightForWidth(self.fdn2intm_3.sizePolicy().hasHeightForWidth())
        self.fdn2intm_3.setSizePolicy(sizePolicy2)
        self.fdn2intm_3.setMinimumSize(QSize(100, 30))
        self.fdn2intm_3.setFont(font)
        self.fdn2intm_3.setAutoFillBackground(False)
        self.fdn2intm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn2intm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn2intm_3.setFrameShape(QFrame.Panel)
        self.fdn2intm_3.setFrameShadow(QFrame.Sunken)
        self.fdn2intm_3.setTextFormat(Qt.AutoText)
        self.fdn2intm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn2intm_3, 2, 5, 1, 1)

        self.fdn2out_btn = QPushButton(self.page1_main)
        self.fdn2out_btn.setObjectName(u"fdn2out_btn")
        self.fdn2out_btn.setMinimumSize(QSize(0, 30))
        self.fdn2out_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn2out_btn, 3, 0, 1, 1)

        self.fdn2outtm = QLabel(self.page1_main)
        self.fdn2outtm.setObjectName(u"fdn2outtm")
        sizePolicy2.setHeightForWidth(self.fdn2outtm.sizePolicy().hasHeightForWidth())
        self.fdn2outtm.setSizePolicy(sizePolicy2)
        self.fdn2outtm.setMinimumSize(QSize(100, 30))
        self.fdn2outtm.setFont(font)
        self.fdn2outtm.setAutoFillBackground(False)
        self.fdn2outtm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn2outtm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn2outtm.setFrameShape(QFrame.Panel)
        self.fdn2outtm.setFrameShadow(QFrame.Sunken)
        self.fdn2outtm.setTextFormat(Qt.AutoText)
        self.fdn2outtm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn2outtm, 3, 1, 1, 1)

        self.fdn2out_btn_2 = QPushButton(self.page1_main)
        self.fdn2out_btn_2.setObjectName(u"fdn2out_btn_2")
        self.fdn2out_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn2out_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn2out_btn_2, 3, 2, 1, 1)

        self.fdn2outtm_2 = QLabel(self.page1_main)
        self.fdn2outtm_2.setObjectName(u"fdn2outtm_2")
        sizePolicy2.setHeightForWidth(self.fdn2outtm_2.sizePolicy().hasHeightForWidth())
        self.fdn2outtm_2.setSizePolicy(sizePolicy2)
        self.fdn2outtm_2.setMinimumSize(QSize(100, 30))
        self.fdn2outtm_2.setFont(font)
        self.fdn2outtm_2.setAutoFillBackground(False)
        self.fdn2outtm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn2outtm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn2outtm_2.setFrameShape(QFrame.Panel)
        self.fdn2outtm_2.setFrameShadow(QFrame.Sunken)
        self.fdn2outtm_2.setTextFormat(Qt.AutoText)
        self.fdn2outtm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn2outtm_2, 3, 3, 1, 1)

        self.fdn2out_btn_3 = QPushButton(self.page1_main)
        self.fdn2out_btn_3.setObjectName(u"fdn2out_btn_3")
        self.fdn2out_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn2out_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn2out_btn_3, 3, 4, 1, 1)

        self.fdn2outtm_3 = QLabel(self.page1_main)
        self.fdn2outtm_3.setObjectName(u"fdn2outtm_3")
        sizePolicy2.setHeightForWidth(self.fdn2outtm_3.sizePolicy().hasHeightForWidth())
        self.fdn2outtm_3.setSizePolicy(sizePolicy2)
        self.fdn2outtm_3.setMinimumSize(QSize(100, 30))
        self.fdn2outtm_3.setFont(font)
        self.fdn2outtm_3.setAutoFillBackground(False)
        self.fdn2outtm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn2outtm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn2outtm_3.setFrameShape(QFrame.Panel)
        self.fdn2outtm_3.setFrameShadow(QFrame.Sunken)
        self.fdn2outtm_3.setTextFormat(Qt.AutoText)
        self.fdn2outtm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn2outtm_3, 3, 5, 1, 1)

        self.fdn3in_btn = QPushButton(self.page1_main)
        self.fdn3in_btn.setObjectName(u"fdn3in_btn")
        self.fdn3in_btn.setMinimumSize(QSize(0, 30))
        self.fdn3in_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn3in_btn, 4, 0, 1, 1)

        self.fdn3intm = QLabel(self.page1_main)
        self.fdn3intm.setObjectName(u"fdn3intm")
        sizePolicy2.setHeightForWidth(self.fdn3intm.sizePolicy().hasHeightForWidth())
        self.fdn3intm.setSizePolicy(sizePolicy2)
        self.fdn3intm.setMinimumSize(QSize(100, 30))
        self.fdn3intm.setFont(font)
        self.fdn3intm.setAutoFillBackground(False)
        self.fdn3intm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn3intm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn3intm.setFrameShape(QFrame.Panel)
        self.fdn3intm.setFrameShadow(QFrame.Sunken)
        self.fdn3intm.setTextFormat(Qt.AutoText)
        self.fdn3intm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn3intm, 4, 1, 1, 1)

        self.fdn3in_btn_2 = QPushButton(self.page1_main)
        self.fdn3in_btn_2.setObjectName(u"fdn3in_btn_2")
        self.fdn3in_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn3in_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn3in_btn_2, 4, 2, 1, 1)

        self.fdn3intm_2 = QLabel(self.page1_main)
        self.fdn3intm_2.setObjectName(u"fdn3intm_2")
        sizePolicy2.setHeightForWidth(self.fdn3intm_2.sizePolicy().hasHeightForWidth())
        self.fdn3intm_2.setSizePolicy(sizePolicy2)
        self.fdn3intm_2.setMinimumSize(QSize(100, 30))
        self.fdn3intm_2.setFont(font)
        self.fdn3intm_2.setAutoFillBackground(False)
        self.fdn3intm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn3intm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn3intm_2.setFrameShape(QFrame.Panel)
        self.fdn3intm_2.setFrameShadow(QFrame.Sunken)
        self.fdn3intm_2.setTextFormat(Qt.AutoText)
        self.fdn3intm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn3intm_2, 4, 3, 1, 1)

        self.fdn3in_btn_3 = QPushButton(self.page1_main)
        self.fdn3in_btn_3.setObjectName(u"fdn3in_btn_3")
        self.fdn3in_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn3in_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn3in_btn_3, 4, 4, 1, 1)

        self.fdn3intm_3 = QLabel(self.page1_main)
        self.fdn3intm_3.setObjectName(u"fdn3intm_3")
        sizePolicy2.setHeightForWidth(self.fdn3intm_3.sizePolicy().hasHeightForWidth())
        self.fdn3intm_3.setSizePolicy(sizePolicy2)
        self.fdn3intm_3.setMinimumSize(QSize(100, 30))
        self.fdn3intm_3.setFont(font)
        self.fdn3intm_3.setAutoFillBackground(False)
        self.fdn3intm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn3intm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn3intm_3.setFrameShape(QFrame.Panel)
        self.fdn3intm_3.setFrameShadow(QFrame.Sunken)
        self.fdn3intm_3.setTextFormat(Qt.AutoText)
        self.fdn3intm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn3intm_3, 4, 5, 1, 1)

        self.fdn3out_btn = QPushButton(self.page1_main)
        self.fdn3out_btn.setObjectName(u"fdn3out_btn")
        self.fdn3out_btn.setMinimumSize(QSize(0, 30))
        self.fdn3out_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn3out_btn, 5, 0, 1, 1)

        self.fdn3outtm = QLabel(self.page1_main)
        self.fdn3outtm.setObjectName(u"fdn3outtm")
        sizePolicy2.setHeightForWidth(self.fdn3outtm.sizePolicy().hasHeightForWidth())
        self.fdn3outtm.setSizePolicy(sizePolicy2)
        self.fdn3outtm.setMinimumSize(QSize(100, 30))
        self.fdn3outtm.setFont(font)
        self.fdn3outtm.setAutoFillBackground(False)
        self.fdn3outtm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn3outtm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn3outtm.setFrameShape(QFrame.Panel)
        self.fdn3outtm.setFrameShadow(QFrame.Sunken)
        self.fdn3outtm.setTextFormat(Qt.AutoText)
        self.fdn3outtm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn3outtm, 5, 1, 1, 1)

        self.fdn3out_btn_2 = QPushButton(self.page1_main)
        self.fdn3out_btn_2.setObjectName(u"fdn3out_btn_2")
        self.fdn3out_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn3out_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn3out_btn_2, 5, 2, 1, 1)

        self.fdn3outtm_2 = QLabel(self.page1_main)
        self.fdn3outtm_2.setObjectName(u"fdn3outtm_2")
        sizePolicy2.setHeightForWidth(self.fdn3outtm_2.sizePolicy().hasHeightForWidth())
        self.fdn3outtm_2.setSizePolicy(sizePolicy2)
        self.fdn3outtm_2.setMinimumSize(QSize(100, 30))
        self.fdn3outtm_2.setFont(font)
        self.fdn3outtm_2.setAutoFillBackground(False)
        self.fdn3outtm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn3outtm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn3outtm_2.setFrameShape(QFrame.Panel)
        self.fdn3outtm_2.setFrameShadow(QFrame.Sunken)
        self.fdn3outtm_2.setTextFormat(Qt.AutoText)
        self.fdn3outtm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn3outtm_2, 5, 3, 1, 1)

        self.fdn3out_btn_3 = QPushButton(self.page1_main)
        self.fdn3out_btn_3.setObjectName(u"fdn3out_btn_3")
        self.fdn3out_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn3out_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn3out_btn_3, 5, 4, 1, 1)

        self.fdn3outtm_3 = QLabel(self.page1_main)
        self.fdn3outtm_3.setObjectName(u"fdn3outtm_3")
        sizePolicy2.setHeightForWidth(self.fdn3outtm_3.sizePolicy().hasHeightForWidth())
        self.fdn3outtm_3.setSizePolicy(sizePolicy2)
        self.fdn3outtm_3.setMinimumSize(QSize(100, 30))
        self.fdn3outtm_3.setFont(font)
        self.fdn3outtm_3.setAutoFillBackground(False)
        self.fdn3outtm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn3outtm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn3outtm_3.setFrameShape(QFrame.Panel)
        self.fdn3outtm_3.setFrameShadow(QFrame.Sunken)
        self.fdn3outtm_3.setTextFormat(Qt.AutoText)
        self.fdn3outtm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn3outtm_3, 5, 5, 1, 1)

        self.fdn4in_btn = QPushButton(self.page1_main)
        self.fdn4in_btn.setObjectName(u"fdn4in_btn")
        self.fdn4in_btn.setMinimumSize(QSize(0, 30))
        self.fdn4in_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn4in_btn, 6, 0, 1, 1)

        self.fdn4intm = QLabel(self.page1_main)
        self.fdn4intm.setObjectName(u"fdn4intm")
        sizePolicy2.setHeightForWidth(self.fdn4intm.sizePolicy().hasHeightForWidth())
        self.fdn4intm.setSizePolicy(sizePolicy2)
        self.fdn4intm.setMinimumSize(QSize(100, 30))
        self.fdn4intm.setFont(font)
        self.fdn4intm.setAutoFillBackground(False)
        self.fdn4intm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn4intm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn4intm.setFrameShape(QFrame.Panel)
        self.fdn4intm.setFrameShadow(QFrame.Sunken)
        self.fdn4intm.setTextFormat(Qt.AutoText)
        self.fdn4intm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn4intm, 6, 1, 1, 1)

        self.fdn4in_btn_2 = QPushButton(self.page1_main)
        self.fdn4in_btn_2.setObjectName(u"fdn4in_btn_2")
        self.fdn4in_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn4in_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn4in_btn_2, 6, 2, 1, 1)

        self.fdn4intm_2 = QLabel(self.page1_main)
        self.fdn4intm_2.setObjectName(u"fdn4intm_2")
        sizePolicy2.setHeightForWidth(self.fdn4intm_2.sizePolicy().hasHeightForWidth())
        self.fdn4intm_2.setSizePolicy(sizePolicy2)
        self.fdn4intm_2.setMinimumSize(QSize(100, 30))
        self.fdn4intm_2.setFont(font)
        self.fdn4intm_2.setAutoFillBackground(False)
        self.fdn4intm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn4intm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn4intm_2.setFrameShape(QFrame.Panel)
        self.fdn4intm_2.setFrameShadow(QFrame.Sunken)
        self.fdn4intm_2.setTextFormat(Qt.AutoText)
        self.fdn4intm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn4intm_2, 6, 3, 1, 1)

        self.fdn4in_btn_3 = QPushButton(self.page1_main)
        self.fdn4in_btn_3.setObjectName(u"fdn4in_btn_3")
        self.fdn4in_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn4in_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn4in_btn_3, 6, 4, 1, 1)

        self.fdn4intm_3 = QLabel(self.page1_main)
        self.fdn4intm_3.setObjectName(u"fdn4intm_3")
        sizePolicy2.setHeightForWidth(self.fdn4intm_3.sizePolicy().hasHeightForWidth())
        self.fdn4intm_3.setSizePolicy(sizePolicy2)
        self.fdn4intm_3.setMinimumSize(QSize(100, 30))
        self.fdn4intm_3.setFont(font)
        self.fdn4intm_3.setAutoFillBackground(False)
        self.fdn4intm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn4intm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn4intm_3.setFrameShape(QFrame.Panel)
        self.fdn4intm_3.setFrameShadow(QFrame.Sunken)
        self.fdn4intm_3.setTextFormat(Qt.AutoText)
        self.fdn4intm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn4intm_3, 6, 5, 1, 1)

        self.fdn4out_btn = QPushButton(self.page1_main)
        self.fdn4out_btn.setObjectName(u"fdn4out_btn")
        self.fdn4out_btn.setMinimumSize(QSize(0, 30))
        self.fdn4out_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn4out_btn, 7, 0, 1, 1)

        self.fdn4outtm = QLabel(self.page1_main)
        self.fdn4outtm.setObjectName(u"fdn4outtm")
        sizePolicy2.setHeightForWidth(self.fdn4outtm.sizePolicy().hasHeightForWidth())
        self.fdn4outtm.setSizePolicy(sizePolicy2)
        self.fdn4outtm.setMinimumSize(QSize(100, 30))
        self.fdn4outtm.setFont(font)
        self.fdn4outtm.setAutoFillBackground(False)
        self.fdn4outtm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn4outtm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn4outtm.setFrameShape(QFrame.Panel)
        self.fdn4outtm.setFrameShadow(QFrame.Sunken)
        self.fdn4outtm.setTextFormat(Qt.AutoText)
        self.fdn4outtm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn4outtm, 7, 1, 1, 1)

        self.fdn4out_btn_2 = QPushButton(self.page1_main)
        self.fdn4out_btn_2.setObjectName(u"fdn4out_btn_2")
        self.fdn4out_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn4out_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn4out_btn_2, 7, 2, 1, 1)

        self.fdn4outtm_2 = QLabel(self.page1_main)
        self.fdn4outtm_2.setObjectName(u"fdn4outtm_2")
        sizePolicy2.setHeightForWidth(self.fdn4outtm_2.sizePolicy().hasHeightForWidth())
        self.fdn4outtm_2.setSizePolicy(sizePolicy2)
        self.fdn4outtm_2.setMinimumSize(QSize(100, 30))
        self.fdn4outtm_2.setFont(font)
        self.fdn4outtm_2.setAutoFillBackground(False)
        self.fdn4outtm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn4outtm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn4outtm_2.setFrameShape(QFrame.Panel)
        self.fdn4outtm_2.setFrameShadow(QFrame.Sunken)
        self.fdn4outtm_2.setTextFormat(Qt.AutoText)
        self.fdn4outtm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn4outtm_2, 7, 3, 1, 1)

        self.fdn4out_btn_3 = QPushButton(self.page1_main)
        self.fdn4out_btn_3.setObjectName(u"fdn4out_btn_3")
        self.fdn4out_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn4out_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn4out_btn_3, 7, 4, 1, 1)

        self.fdn4outtm_3 = QLabel(self.page1_main)
        self.fdn4outtm_3.setObjectName(u"fdn4outtm_3")
        sizePolicy2.setHeightForWidth(self.fdn4outtm_3.sizePolicy().hasHeightForWidth())
        self.fdn4outtm_3.setSizePolicy(sizePolicy2)
        self.fdn4outtm_3.setMinimumSize(QSize(100, 30))
        self.fdn4outtm_3.setFont(font)
        self.fdn4outtm_3.setAutoFillBackground(False)
        self.fdn4outtm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn4outtm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn4outtm_3.setFrameShape(QFrame.Panel)
        self.fdn4outtm_3.setFrameShadow(QFrame.Sunken)
        self.fdn4outtm_3.setTextFormat(Qt.AutoText)
        self.fdn4outtm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn4outtm_3, 7, 5, 1, 1)

        self.fdn5in_btn = QPushButton(self.page1_main)
        self.fdn5in_btn.setObjectName(u"fdn5in_btn")
        self.fdn5in_btn.setMinimumSize(QSize(0, 30))
        self.fdn5in_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn5in_btn, 8, 0, 1, 1)

        self.fdn5intm = QLabel(self.page1_main)
        self.fdn5intm.setObjectName(u"fdn5intm")
        sizePolicy2.setHeightForWidth(self.fdn5intm.sizePolicy().hasHeightForWidth())
        self.fdn5intm.setSizePolicy(sizePolicy2)
        self.fdn5intm.setMinimumSize(QSize(100, 30))
        self.fdn5intm.setFont(font)
        self.fdn5intm.setAutoFillBackground(False)
        self.fdn5intm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn5intm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn5intm.setFrameShape(QFrame.Panel)
        self.fdn5intm.setFrameShadow(QFrame.Sunken)
        self.fdn5intm.setTextFormat(Qt.AutoText)
        self.fdn5intm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn5intm, 8, 1, 1, 1)

        self.fdn5in_btn_2 = QPushButton(self.page1_main)
        self.fdn5in_btn_2.setObjectName(u"fdn5in_btn_2")
        self.fdn5in_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn5in_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn5in_btn_2, 8, 2, 1, 1)

        self.fdn5intm_2 = QLabel(self.page1_main)
        self.fdn5intm_2.setObjectName(u"fdn5intm_2")
        sizePolicy2.setHeightForWidth(self.fdn5intm_2.sizePolicy().hasHeightForWidth())
        self.fdn5intm_2.setSizePolicy(sizePolicy2)
        self.fdn5intm_2.setMinimumSize(QSize(100, 30))
        self.fdn5intm_2.setFont(font)
        self.fdn5intm_2.setAutoFillBackground(False)
        self.fdn5intm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn5intm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn5intm_2.setFrameShape(QFrame.Panel)
        self.fdn5intm_2.setFrameShadow(QFrame.Sunken)
        self.fdn5intm_2.setTextFormat(Qt.AutoText)
        self.fdn5intm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn5intm_2, 8, 3, 1, 1)

        self.fdn5in_btn_3 = QPushButton(self.page1_main)
        self.fdn5in_btn_3.setObjectName(u"fdn5in_btn_3")
        self.fdn5in_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn5in_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn5in_btn_3, 8, 4, 1, 1)

        self.fdn5intm_3 = QLabel(self.page1_main)
        self.fdn5intm_3.setObjectName(u"fdn5intm_3")
        sizePolicy2.setHeightForWidth(self.fdn5intm_3.sizePolicy().hasHeightForWidth())
        self.fdn5intm_3.setSizePolicy(sizePolicy2)
        self.fdn5intm_3.setMinimumSize(QSize(100, 30))
        self.fdn5intm_3.setFont(font)
        self.fdn5intm_3.setAutoFillBackground(False)
        self.fdn5intm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn5intm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn5intm_3.setFrameShape(QFrame.Panel)
        self.fdn5intm_3.setFrameShadow(QFrame.Sunken)
        self.fdn5intm_3.setTextFormat(Qt.AutoText)
        self.fdn5intm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn5intm_3, 8, 5, 1, 1)

        self.fdn5out_btn = QPushButton(self.page1_main)
        self.fdn5out_btn.setObjectName(u"fdn5out_btn")
        self.fdn5out_btn.setMinimumSize(QSize(0, 30))
        self.fdn5out_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn5out_btn, 9, 0, 1, 1)

        self.fdn5outtm = QLabel(self.page1_main)
        self.fdn5outtm.setObjectName(u"fdn5outtm")
        sizePolicy2.setHeightForWidth(self.fdn5outtm.sizePolicy().hasHeightForWidth())
        self.fdn5outtm.setSizePolicy(sizePolicy2)
        self.fdn5outtm.setMinimumSize(QSize(100, 30))
        self.fdn5outtm.setFont(font)
        self.fdn5outtm.setAutoFillBackground(False)
        self.fdn5outtm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn5outtm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn5outtm.setFrameShape(QFrame.Panel)
        self.fdn5outtm.setFrameShadow(QFrame.Sunken)
        self.fdn5outtm.setTextFormat(Qt.AutoText)
        self.fdn5outtm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn5outtm, 9, 1, 1, 1)

        self.fdn5out_btn_2 = QPushButton(self.page1_main)
        self.fdn5out_btn_2.setObjectName(u"fdn5out_btn_2")
        self.fdn5out_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn5out_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn5out_btn_2, 9, 2, 1, 1)

        self.fdn5outtm_2 = QLabel(self.page1_main)
        self.fdn5outtm_2.setObjectName(u"fdn5outtm_2")
        sizePolicy2.setHeightForWidth(self.fdn5outtm_2.sizePolicy().hasHeightForWidth())
        self.fdn5outtm_2.setSizePolicy(sizePolicy2)
        self.fdn5outtm_2.setMinimumSize(QSize(100, 30))
        self.fdn5outtm_2.setFont(font)
        self.fdn5outtm_2.setAutoFillBackground(False)
        self.fdn5outtm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn5outtm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn5outtm_2.setFrameShape(QFrame.Panel)
        self.fdn5outtm_2.setFrameShadow(QFrame.Sunken)
        self.fdn5outtm_2.setTextFormat(Qt.AutoText)
        self.fdn5outtm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn5outtm_2, 9, 3, 1, 1)

        self.fdn5out_btn_3 = QPushButton(self.page1_main)
        self.fdn5out_btn_3.setObjectName(u"fdn5out_btn_3")
        self.fdn5out_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn5out_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn5out_btn_3, 9, 4, 1, 1)

        self.fdn5outtm_3 = QLabel(self.page1_main)
        self.fdn5outtm_3.setObjectName(u"fdn5outtm_3")
        sizePolicy2.setHeightForWidth(self.fdn5outtm_3.sizePolicy().hasHeightForWidth())
        self.fdn5outtm_3.setSizePolicy(sizePolicy2)
        self.fdn5outtm_3.setMinimumSize(QSize(100, 30))
        self.fdn5outtm_3.setFont(font)
        self.fdn5outtm_3.setAutoFillBackground(False)
        self.fdn5outtm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn5outtm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn5outtm_3.setFrameShape(QFrame.Panel)
        self.fdn5outtm_3.setFrameShadow(QFrame.Sunken)
        self.fdn5outtm_3.setTextFormat(Qt.AutoText)
        self.fdn5outtm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn5outtm_3, 9, 5, 1, 1)

        self.fdn6in_btn = QPushButton(self.page1_main)
        self.fdn6in_btn.setObjectName(u"fdn6in_btn")
        self.fdn6in_btn.setMinimumSize(QSize(0, 30))
        self.fdn6in_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn6in_btn, 10, 0, 1, 1)

        self.fdn6intm = QLabel(self.page1_main)
        self.fdn6intm.setObjectName(u"fdn6intm")
        sizePolicy2.setHeightForWidth(self.fdn6intm.sizePolicy().hasHeightForWidth())
        self.fdn6intm.setSizePolicy(sizePolicy2)
        self.fdn6intm.setMinimumSize(QSize(100, 30))
        self.fdn6intm.setFont(font)
        self.fdn6intm.setAutoFillBackground(False)
        self.fdn6intm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn6intm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn6intm.setFrameShape(QFrame.Panel)
        self.fdn6intm.setFrameShadow(QFrame.Sunken)
        self.fdn6intm.setTextFormat(Qt.AutoText)
        self.fdn6intm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn6intm, 10, 1, 1, 1)

        self.fdn6in_btn_2 = QPushButton(self.page1_main)
        self.fdn6in_btn_2.setObjectName(u"fdn6in_btn_2")
        self.fdn6in_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn6in_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn6in_btn_2, 10, 2, 1, 1)

        self.fdn6intm_2 = QLabel(self.page1_main)
        self.fdn6intm_2.setObjectName(u"fdn6intm_2")
        sizePolicy2.setHeightForWidth(self.fdn6intm_2.sizePolicy().hasHeightForWidth())
        self.fdn6intm_2.setSizePolicy(sizePolicy2)
        self.fdn6intm_2.setMinimumSize(QSize(100, 30))
        self.fdn6intm_2.setFont(font)
        self.fdn6intm_2.setAutoFillBackground(False)
        self.fdn6intm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn6intm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn6intm_2.setFrameShape(QFrame.Panel)
        self.fdn6intm_2.setFrameShadow(QFrame.Sunken)
        self.fdn6intm_2.setTextFormat(Qt.AutoText)
        self.fdn6intm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn6intm_2, 10, 3, 1, 1)

        self.fdn6in_btn_3 = QPushButton(self.page1_main)
        self.fdn6in_btn_3.setObjectName(u"fdn6in_btn_3")
        self.fdn6in_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn6in_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn6in_btn_3, 10, 4, 1, 1)

        self.fdn6intm_3 = QLabel(self.page1_main)
        self.fdn6intm_3.setObjectName(u"fdn6intm_3")
        sizePolicy2.setHeightForWidth(self.fdn6intm_3.sizePolicy().hasHeightForWidth())
        self.fdn6intm_3.setSizePolicy(sizePolicy2)
        self.fdn6intm_3.setMinimumSize(QSize(100, 30))
        self.fdn6intm_3.setFont(font)
        self.fdn6intm_3.setAutoFillBackground(False)
        self.fdn6intm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn6intm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn6intm_3.setFrameShape(QFrame.Panel)
        self.fdn6intm_3.setFrameShadow(QFrame.Sunken)
        self.fdn6intm_3.setTextFormat(Qt.AutoText)
        self.fdn6intm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn6intm_3, 10, 5, 1, 1)

        self.fdn6out_btn = QPushButton(self.page1_main)
        self.fdn6out_btn.setObjectName(u"fdn6out_btn")
        self.fdn6out_btn.setMinimumSize(QSize(0, 30))
        self.fdn6out_btn.setFont(font)

        self.gridLayout_2.addWidget(self.fdn6out_btn, 11, 0, 1, 1)

        self.fdn6outtm = QLabel(self.page1_main)
        self.fdn6outtm.setObjectName(u"fdn6outtm")
        sizePolicy2.setHeightForWidth(self.fdn6outtm.sizePolicy().hasHeightForWidth())
        self.fdn6outtm.setSizePolicy(sizePolicy2)
        self.fdn6outtm.setMinimumSize(QSize(100, 30))
        self.fdn6outtm.setFont(font)
        self.fdn6outtm.setAutoFillBackground(False)
        self.fdn6outtm.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn6outtm.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn6outtm.setFrameShape(QFrame.Panel)
        self.fdn6outtm.setFrameShadow(QFrame.Sunken)
        self.fdn6outtm.setTextFormat(Qt.AutoText)
        self.fdn6outtm.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn6outtm, 11, 1, 1, 1)

        self.fdn6out_btn_2 = QPushButton(self.page1_main)
        self.fdn6out_btn_2.setObjectName(u"fdn6out_btn_2")
        self.fdn6out_btn_2.setMinimumSize(QSize(0, 30))
        self.fdn6out_btn_2.setFont(font)

        self.gridLayout_2.addWidget(self.fdn6out_btn_2, 11, 2, 1, 1)

        self.fdn6outtm_2 = QLabel(self.page1_main)
        self.fdn6outtm_2.setObjectName(u"fdn6outtm_2")
        sizePolicy2.setHeightForWidth(self.fdn6outtm_2.sizePolicy().hasHeightForWidth())
        self.fdn6outtm_2.setSizePolicy(sizePolicy2)
        self.fdn6outtm_2.setMinimumSize(QSize(100, 30))
        self.fdn6outtm_2.setFont(font)
        self.fdn6outtm_2.setAutoFillBackground(False)
        self.fdn6outtm_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn6outtm_2.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn6outtm_2.setFrameShape(QFrame.Panel)
        self.fdn6outtm_2.setFrameShadow(QFrame.Sunken)
        self.fdn6outtm_2.setTextFormat(Qt.AutoText)
        self.fdn6outtm_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn6outtm_2, 11, 3, 1, 1)

        self.fdn6out_btn_3 = QPushButton(self.page1_main)
        self.fdn6out_btn_3.setObjectName(u"fdn6out_btn_3")
        self.fdn6out_btn_3.setMinimumSize(QSize(0, 30))
        self.fdn6out_btn_3.setFont(font)

        self.gridLayout_2.addWidget(self.fdn6out_btn_3, 11, 4, 1, 1)

        self.fdn6outtm_3 = QLabel(self.page1_main)
        self.fdn6outtm_3.setObjectName(u"fdn6outtm_3")
        sizePolicy2.setHeightForWidth(self.fdn6outtm_3.sizePolicy().hasHeightForWidth())
        self.fdn6outtm_3.setSizePolicy(sizePolicy2)
        self.fdn6outtm_3.setMinimumSize(QSize(100, 30))
        self.fdn6outtm_3.setFont(font)
        self.fdn6outtm_3.setAutoFillBackground(False)
        self.fdn6outtm_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fdn6outtm_3.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.fdn6outtm_3.setFrameShape(QFrame.Panel)
        self.fdn6outtm_3.setFrameShadow(QFrame.Sunken)
        self.fdn6outtm_3.setTextFormat(Qt.AutoText)
        self.fdn6outtm_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.fdn6outtm_3, 11, 5, 1, 1)

        self.stackedWidget.addWidget(self.page1_main)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.stackedWidget.addWidget(self.page_2)

        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)


        self.gridLayout_5.addWidget(self.frame, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exit_btn.clicked.connect(MainWindow.close)

        self.stackedWidget.setCurrentIndex(0)
        self.fdn1in_btn.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u822a\u680f", None))
        self.temperature_btn.setText(QCoreApplication.translate("MainWindow", u"\u6e29\u5ea6\u76d1\u63a7", None))
        self.history_btn.setText(QCoreApplication.translate("MainWindow", u"\u5386\u53f2\u6570\u636e", None))
        self.client_setup_btn.setText(QCoreApplication.translate("MainWindow", u"\u7ad9\u70b9\u8bbe\u7f6e", None))
        self.exit_btn.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#if QT_CONFIG(tooltip)
        self.fdn1in_btn.setToolTip(QCoreApplication.translate("MainWindow", u"tooltip", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.fdn1in_btn.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.fdn1in_btn.setText(QCoreApplication.translate("MainWindow", u"1#\u51b7\u4e95\u8fdb\u6db2", None))
#if QT_CONFIG(shortcut)
        self.fdn1in_btn.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.fdn1intm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn1in_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn1in_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn1intm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn1in_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn1in_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn1intm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn1out_brn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn1out_brn.setText(QCoreApplication.translate("MainWindow", u"1#\u51b7\u4e95\u56de\u6c14", None))
        self.fdn1outtm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn1out_brn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn1out_brn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn1outtm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn1out_brn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn1out_brn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn1outtm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn2in_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn2in_btn.setText(QCoreApplication.translate("MainWindow", u"2#\u51b7\u4e95\u8fdb\u6db2", None))
        self.fdn2intm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn2in_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn2in_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn2intm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn2in_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn2in_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn2intm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn2out_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn2out_btn.setText(QCoreApplication.translate("MainWindow", u"2#\u51b7\u4e95\u56de\u6c14", None))
        self.fdn2outtm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn2out_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn2out_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn2outtm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn2out_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn2out_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn2outtm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn3in_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn3in_btn.setText(QCoreApplication.translate("MainWindow", u"3#\u51b7\u4e95\u8fdb\u6db2", None))
        self.fdn3intm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn3in_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn3in_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn3intm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn3in_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn3in_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn3intm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn3out_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn3out_btn.setText(QCoreApplication.translate("MainWindow", u"3#\u51b7\u4e95\u56de\u6c14", None))
        self.fdn3outtm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn3out_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn3out_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn3outtm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(tooltip)
        self.fdn3out_btn_3.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.fdn3out_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn3out_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn3outtm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn4in_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn4in_btn.setText(QCoreApplication.translate("MainWindow", u"4#\u51b7\u4e95\u8fdb\u6db2", None))
        self.fdn4intm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(tooltip)
        self.fdn4in_btn_2.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#2ec27e;\">\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.fdn4in_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn4in_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn4intm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn4in_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn4in_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn4intm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn4out_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn4out_btn.setText(QCoreApplication.translate("MainWindow", u"4#\u51b7\u4e95\u56de\u6c14", None))
        self.fdn4outtm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn4out_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn4out_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn4outtm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn4out_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn4out_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn4outtm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn5in_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn5in_btn.setText(QCoreApplication.translate("MainWindow", u"5#\u51b7\u4e95\u8fdb\u6db2", None))
        self.fdn5intm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
        self.fdn5in_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn5intm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn5in_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn5in_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn5intm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn5out_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn5out_btn.setText(QCoreApplication.translate("MainWindow", u"5#\u51b7\u4e95\u56de\u6c14", None))
        self.fdn5outtm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn5out_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn5out_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn5outtm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn5out_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn5out_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn5outtm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn6in_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn6in_btn.setText(QCoreApplication.translate("MainWindow", u"6#\u51b7\u4e95\u8fdb\u6db2", None))
        self.fdn6intm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn6in_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn6in_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn6intm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn6in_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn6in_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn6intm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn6out_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn6out_btn.setText(QCoreApplication.translate("MainWindow", u"6#\u51b7\u4e95\u56de\u6c14", None))
        self.fdn6outtm.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn6out_btn_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn6out_btn_2.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn6outtm_2.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
#if QT_CONFIG(statustip)
        self.fdn6out_btn_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6309\u94ae\u6309\u4e0b\uff0c\u62a5\u8b66\u503c\u5f00\u59cb\u542f\u7528", None))
#endif // QT_CONFIG(statustip)
        self.fdn6out_btn_3.setText(QCoreApplication.translate("MainWindow", u"\u5907\u7528", None))
        self.fdn6outtm_3.setText(QCoreApplication.translate("MainWindow", u"00.0", None))
    # retranslateUi

